services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: "no"
    ports:
      - "27025:27017"
    volumes:
      - mongo-data:/data/db
  restart: "no"

volumes:
  mongo-data: